const questoes = [
  {
    id: 1,
    disciplina: "Português",
    assunto: "Ortografia",
    enunciado: "Qual é a forma correta de escrever?",
    alternativas: ["Excessão", "Exceção", "Exceçâo", "Exceçom"],
    respostaCorreta: 1,
  },
  {
    id: 2,
    disciplina: "Português",
    assunto: "Gramática",
    enunciado: "Qual palavra é um verbo?",
    alternativas: ["Casa", "Bonito", "Correr", "Mesa"],
    respostaCorreta: 2,
  },
  {
    id: 3,
    disciplina: "Português",
    assunto: "Interpretação",
    enunciado: "Em 'O gato dorme no sofá', quem está dormindo?",
    alternativas: ["O sofá", "O gato", "O dono", "Ninguém"],
    respostaCorreta: 1,
  },
  {
    id: 4,
    disciplina: "Português",
    assunto: "Plural",
    enunciado: "Qual é o plural de 'cão'?",
    alternativas: ["Cães", "Cãos", "Cãons", "Cãez"],
    respostaCorreta: 0,
  },
  {
    id: 5,
    disciplina: "Português",
    assunto: "Acentuação",
    enunciado: "Qual das palavras está corretamente acentuada?",
    alternativas: ["Heroi", "Herói", "Heroís", "Heróii"],
    respostaCorreta: 1,
  },
  {
    id: 6,
    disciplina: "Português",
    assunto: "Sinônimos",
    enunciado: "Qual palavra é sinônimo de 'alegre'?",
    alternativas: ["Triste", "Contente", "Zangado", "Cansado"],
    respostaCorreta: 1,
  },
  {
    id: 7,
    disciplina: "Português",
    assunto: "Antônimos",
    enunciado: "Qual é o antônimo de 'generoso'?",
    alternativas: ["Bondoso", "Solidário", "Egoísta", "Gentil"],
    respostaCorreta: 2,
  },
  {
    id: 8,
    disciplina: "Português",
    assunto: "Classes de palavras",
    enunciado: "Qual palavra é um substantivo?",
    alternativas: ["Escola", "Rapidamente", "Estudar", "Belo"],
    respostaCorreta: 0,
  },
  {
    id: 9,
    disciplina: "Português",
    assunto: "Adjetivos",
    enunciado: "Em 'A menina curiosa abriu o livro', qual palavra é um adjetivo?",
    alternativas: ["Menina", "Abriu", "Livro", "Curiosa"],
    respostaCorreta: 3,
  },
  {
    id: 10,
    disciplina: "Português",
    assunto: "Concordância verbal",
    enunciado: "Qual frase apresenta concordância verbal correta?",
    alternativas: ["Os alunos estuda.", "Os alunos estudam.", "Os aluno estudam.", "Os alunos estudamos."],
    respostaCorreta: 1,
  },
  {
    id: 11,
    disciplina: "Português",
    assunto: "Tempos verbais",
    enunciado: "Em 'Ontem, Pedro viajou', o verbo indica uma ação em qual tempo?",
    alternativas: ["Futuro do presente", "Presente", "Pretérito perfeito", "Futuro do pretérito"],
    respostaCorreta: 2,
  },
  {
    id: 12,
    disciplina: "Português",
    assunto: "Pronomes",
    enunciado: "Qual palavra é um pronome pessoal do caso reto?",
    alternativas: ["Eu", "Meu", "Este", "Alguém"],
    respostaCorreta: 0,
  },
  {
    id: 13,
    disciplina: "Português",
    assunto: "Pontuação",
    enunciado: "Qual sinal deve encerrar uma pergunta direta?",
    alternativas: ["Ponto-final", "Vírgula", "Dois-pontos", "Ponto de interrogação"],
    respostaCorreta: 3,
  },
  {
    id: 14,
    disciplina: "Português",
    assunto: "Divisão silábica",
    enunciado: "Qual é a divisão silábica correta de 'janela'?",
    alternativas: ["Jan-e-la", "Ja-ne-la", "Ja-nel-a", "J-a-ne-la"],
    respostaCorreta: 1,
  },
  {
    id: 15,
    disciplina: "Português",
    assunto: "Sílaba tônica",
    enunciado: "Qual é a sílaba tônica da palavra 'café'?",
    alternativas: ["Ca", "Caf", "Fé", "A"],
    respostaCorreta: 2,
  },
  {
    id: 16,
    disciplina: "Português",
    assunto: "Ortografia",
    enunciado: "Qual palavra está escrita corretamente?",
    alternativas: ["Privilégio", "Previlegio", "Priviléjio", "Previlejio"],
    respostaCorreta: 0,
  },
  {
    id: 17,
    disciplina: "Português",
    assunto: "Sujeito",
    enunciado: "Em 'As crianças brincaram no parque', qual é o sujeito?",
    alternativas: ["No parque", "Brincaram", "Parque", "As crianças"],
    respostaCorreta: 3,
  },
  {
    id: 18,
    disciplina: "Matemática",
    assunto: "Adição",
    enunciado: "Quanto é 37 + 28?",
    alternativas: ["55", "65", "75", "63"],
    respostaCorreta: 1,
  },
  {
    id: 19,
    disciplina: "Matemática",
    assunto: "Subtração",
    enunciado: "Quanto é 90 - 46?",
    alternativas: ["54", "46", "44", "56"],
    respostaCorreta: 2,
  },
  {
    id: 20,
    disciplina: "Matemática",
    assunto: "Multiplicação",
    enunciado: "Quanto é 8 × 7?",
    alternativas: ["56", "54", "64", "48"],
    respostaCorreta: 0,
  },
  {
    id: 21,
    disciplina: "Matemática",
    assunto: "Divisão",
    enunciado: "Quanto é 144 ÷ 12?",
    alternativas: ["10", "11", "14", "12"],
    respostaCorreta: 3,
  },
  {
    id: 22,
    disciplina: "Matemática",
    assunto: "Frações",
    enunciado: "Quanto é 1/2 + 1/4?",
    alternativas: ["2/6", "3/4", "1/8", "2/4"],
    respostaCorreta: 1,
  },
  {
    id: 23,
    disciplina: "Matemática",
    assunto: "Porcentagem",
    enunciado: "Quanto é 20% de 150?",
    alternativas: ["20", "25", "30", "35"],
    respostaCorreta: 2,
  },
  {
    id: 24,
    disciplina: "Matemática",
    assunto: "Equação do primeiro grau",
    enunciado: "Qual é o valor de x em 3x + 5 = 20?",
    alternativas: ["5", "10", "15", "3"],
    respostaCorreta: 0,
  },
  {
    id: 25,
    disciplina: "Matemática",
    assunto: "Área",
    enunciado: "Qual é a área de um retângulo de 8 cm de comprimento e 5 cm de largura?",
    alternativas: ["13 cm²", "26 cm²", "80 cm²", "40 cm²"],
    respostaCorreta: 3,
  },
  {
    id: 26,
    disciplina: "Matemática",
    assunto: "Perímetro",
    enunciado: "Qual é o perímetro de um quadrado com lado de 6 cm?",
    alternativas: ["12 cm", "24 cm", "36 cm", "18 cm"],
    respostaCorreta: 1,
  },
  {
    id: 27,
    disciplina: "Matemática",
    assunto: "Média aritmética",
    enunciado: "Qual é a média aritmética de 6, 8 e 10?",
    alternativas: ["6", "7", "8", "9"],
    respostaCorreta: 2,
  },
  {
    id: 28,
    disciplina: "Matemática",
    assunto: "Números decimais",
    enunciado: "Quanto é 2,5 + 1,75?",
    alternativas: ["4,25", "3,25", "4,75", "3,75"],
    respostaCorreta: 0,
  },
  {
    id: 29,
    disciplina: "Matemática",
    assunto: "Potenciação",
    enunciado: "Qual é o valor de 2 elevado à quinta potência?",
    alternativas: ["10", "16", "25", "32"],
    respostaCorreta: 3,
  },
  {
    id: 30,
    disciplina: "Matemática",
    assunto: "Raiz quadrada",
    enunciado: "Qual é a raiz quadrada positiva de 81?",
    alternativas: ["8", "9", "18", "27"],
    respostaCorreta: 1,
  },
  {
    id: 31,
    disciplina: "Matemática",
    assunto: "Unidades de medida",
    enunciado: "Quantos metros correspondem a 3,5 quilômetros?",
    alternativas: ["35", "350", "3500", "35000"],
    respostaCorreta: 2,
  },
  {
    id: 32,
    disciplina: "Matemática",
    assunto: "Probabilidade",
    enunciado: "Ao lançar um dado comum de seis faces, qual é a probabilidade de sair um número par?",
    alternativas: ["1/2", "1/3", "1/6", "2/3"],
    respostaCorreta: 0,
  },
  {
    id: 33,
    disciplina: "Matemática",
    assunto: "Proporcionalidade",
    enunciado: "Se 3 cadernos custam R$ 18, quanto custam 5 cadernos do mesmo preço unitário?",
    alternativas: ["R$ 24", "R$ 36", "R$ 25", "R$ 30"],
    respostaCorreta: 3,
  },
  {
    id: 34,
    disciplina: "Matemática",
    assunto: "Ângulos",
    enunciado: "Dois ângulos internos de um triângulo medem 50° e 60°. Quanto mede o terceiro?",
    alternativas: ["60°", "70°", "80°", "90°"],
    respostaCorreta: 1,
  },
  {
    id: 35,
    disciplina: "Raciocínio Lógico",
    assunto: "Sequências numéricas",
    enunciado: "Qual é o próximo número da sequência 2, 4, 8, 16, em que cada termo é o dobro do anterior?",
    alternativas: ["18", "24", "32", "64"],
    respostaCorreta: 2,
  },
  {
    id: 36,
    disciplina: "Raciocínio Lógico",
    assunto: "Sequências numéricas",
    enunciado: "Qual é o próximo número da sequência 3, 6, 9, 12, que aumenta de 3 em 3?",
    alternativas: ["15", "14", "18", "16"],
    respostaCorreta: 0,
  },
  {
    id: 37,
    disciplina: "Raciocínio Lógico",
    assunto: "Sequências de letras",
    enunciado: "No alfabeto de 26 letras, qual letra completa A, C, E, G, pulando sempre uma letra?",
    alternativas: ["H", "J", "K", "I"],
    respostaCorreta: 3,
  },
  {
    id: 38,
    disciplina: "Raciocínio Lógico",
    assunto: "Dedução",
    enunciado: "Todos os gatos são mamíferos. Mimi é um gato. O que se pode concluir?",
    alternativas: ["Mimi é uma ave.", "Mimi é um mamífero.", "Todo mamífero é um gato.", "Mimi não é um animal."],
    respostaCorreta: 1,
  },
  {
    id: 39,
    disciplina: "Raciocínio Lógico",
    assunto: "Negação",
    enunciado: "Qual é a negação de 'Todos os alunos chegaram'?",
    alternativas: ["Nenhum aluno chegou.", "Todos os alunos saíram.", "Pelo menos um aluno não chegou.", "Apenas um aluno chegou."],
    respostaCorreta: 2,
  },
  {
    id: 40,
    disciplina: "Raciocínio Lógico",
    assunto: "Condicional",
    enunciado: "Se chove, a rua fica molhada. Está chovendo. Qual conclusão decorre dessas informações?",
    alternativas: ["A rua fica molhada.", "A rua fica seca.", "Não está chovendo.", "A chuva já terminou."],
    respostaCorreta: 0,
  },
  {
    id: 41,
    disciplina: "Raciocínio Lógico",
    assunto: "Ordenação",
    enunciado: "Ana é mais alta que Bia, e Bia é mais alta que Caio. Quem é a pessoa mais baixa entre os três?",
    alternativas: ["Ana", "Bia", "Não é possível determinar.", "Caio"],
    respostaCorreta: 3,
  },
  {
    id: 42,
    disciplina: "Raciocínio Lógico",
    assunto: "Calendário",
    enunciado: "Se hoje é segunda-feira, que dia da semana será daqui a 10 dias?",
    alternativas: ["Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"],
    respostaCorreta: 1,
  },
  {
    id: 43,
    disciplina: "Raciocínio Lógico",
    assunto: "Contagem",
    enunciado: "Quantas combinações diferentes podem ser feitas escolhendo uma camiseta entre 3 e uma calça entre 2?",
    alternativas: ["5", "8", "6", "9"],
    respostaCorreta: 2,
  },
  {
    id: 44,
    disciplina: "Raciocínio Lógico",
    assunto: "Conjuntos",
    enunciado: "Em uma turma, 12 alunos gostam de futebol, 8 de vôlei e 3 dos dois. Quantos gostam de pelo menos um desses esportes?",
    alternativas: ["17", "20", "23", "15"],
    respostaCorreta: 0,
  },
  {
    id: 45,
    disciplina: "Raciocínio Lógico",
    assunto: "Princípio das gavetas",
    enunciado: "Uma gaveta tem meias pretas e brancas em quantidade suficiente. Sem olhar, quantas meias é preciso retirar para garantir duas da mesma cor?",
    alternativas: ["1", "2", "4", "3"],
    respostaCorreta: 3,
  },
  {
    id: 46,
    disciplina: "Raciocínio Lógico",
    assunto: "Posições",
    enunciado: "Em uma fila, Lucas é o quarto a partir do início e o terceiro a partir do fim. Quantas pessoas estão na fila?",
    alternativas: ["5", "6", "7", "8"],
    respostaCorreta: 1,
  },
  {
    id: 47,
    disciplina: "Raciocínio Lógico",
    assunto: "Conjunção",
    enunciado: "Quando a proposição 'P e Q' é verdadeira?",
    alternativas: ["Quando apenas P é verdadeira.", "Quando apenas Q é verdadeira.", "Quando P e Q são verdadeiras.", "Quando P e Q são falsas."],
    respostaCorreta: 2,
  },
  {
    id: 48,
    disciplina: "Raciocínio Lógico",
    assunto: "Disjunção",
    enunciado: "Na lógica, considerando o 'ou' inclusivo, quando 'P ou Q' é falsa?",
    alternativas: ["Quando P e Q são falsas.", "Quando P é verdadeira e Q é falsa.", "Quando P é falsa e Q é verdadeira.", "Quando P e Q são verdadeiras."],
    respostaCorreta: 0,
  },
  {
    id: 49,
    disciplina: "Raciocínio Lógico",
    assunto: "Equivalência lógica",
    enunciado: "Qual afirmação é equivalente a 'Se estudo, então aprendo'?",
    alternativas: ["Se aprendo, então estudo.", "Se não estudo, então não aprendo.", "Estudo e não aprendo.", "Se não aprendo, então não estudo."],
    respostaCorreta: 3,
  },
  {
    id: 50,
    disciplina: "Raciocínio Lógico",
    assunto: "Sequência alternada",
    enunciado: "Qual número vem após 1, 4, 2, 5, 3, 6, alternando as sequências 1, 2, 3... e 4, 5, 6...?",
    alternativas: ["7", "4", "8", "5"],
    respostaCorreta: 1,
  },
  {
    id: 51,
    disciplina: "Raciocínio Lógico",
    assunto: "Ordenação temporal",
    enunciado: "João chegou antes de Maria, e Maria chegou antes de Pedro. Quem chegou primeiro entre os três?",
    alternativas: ["Pedro", "Maria", "João", "Todos chegaram juntos."],
    respostaCorreta: 2,
  },
  {
    id: 52,
    disciplina: "Geografia",
    assunto: "Continentes",
    enunciado: "Em qual continente está localizado o Brasil?",
    alternativas: ["América do Sul", "Europa", "Ásia", "África"],
    respostaCorreta: 0,
  },
  {
    id: 53,
    disciplina: "Geografia",
    assunto: "Oceanos",
    enunciado: "Qual oceano banha o litoral brasileiro?",
    alternativas: ["Pacífico", "Índico", "Glacial Ártico", "Atlântico"],
    respostaCorreta: 3,
  },
  {
    id: 54,
    disciplina: "Geografia",
    assunto: "Pontos cardeais",
    enunciado: "Qual ponto cardeal é oposto ao norte?",
    alternativas: ["Leste", "Sul", "Oeste", "Nordeste"],
    respostaCorreta: 1,
  },
  {
    id: 55,
    disciplina: "Geografia",
    assunto: "Coordenadas geográficas",
    enunciado: "A latitude mede a distância angular de um lugar em relação a qual referência?",
    alternativas: ["Meridiano de Greenwich", "Trópico de Capricórnio", "Linha do Equador", "Círculo Polar Ártico"],
    respostaCorreta: 2,
  },
  {
    id: 56,
    disciplina: "Geografia",
    assunto: "Coordenadas geográficas",
    enunciado: "Qual é o meridiano de referência para medir a longitude?",
    alternativas: ["Meridiano de Greenwich", "Linha do Equador", "Trópico de Câncer", "Trópico de Capricórnio"],
    respostaCorreta: 0,
  },
  {
    id: 57,
    disciplina: "Geografia",
    assunto: "Movimentos da Terra",
    enunciado: "Qual movimento da Terra explica a alternância entre dia e noite?",
    alternativas: ["Translação", "Revolução lunar", "Precessão", "Rotação"],
    respostaCorreta: 3,
  },
  {
    id: 58,
    disciplina: "Geografia",
    assunto: "Estações do ano",
    enunciado: "Qual combinação explica as estações do ano na Terra?",
    alternativas: ["Rotação e fases da Lua", "Translação e inclinação do eixo terrestre", "Marés e ventos", "Longitude e altitude"],
    respostaCorreta: 1,
  },
  {
    id: 59,
    disciplina: "Geografia",
    assunto: "Cartografia",
    enunciado: "Em um mapa na escala 1:100.000, 1 cm representa qual distância real?",
    alternativas: ["10 m", "100 m", "1 km", "10 km"],
    respostaCorreta: 2,
  },
  {
    id: 60,
    disciplina: "Geografia",
    assunto: "Biomas brasileiros",
    enunciado: "Qual bioma brasileiro é caracterizado por vegetação adaptada ao clima semiárido?",
    alternativas: ["Caatinga", "Pampa", "Pantanal", "Mata Atlântica"],
    respostaCorreta: 0,
  },
  {
    id: 61,
    disciplina: "Geografia",
    assunto: "Hidrografia",
    enunciado: "Qual termo designa o local onde um rio começa?",
    alternativas: ["Foz", "Margem", "Afluente", "Nascente"],
    respostaCorreta: 3,
  },
  {
    id: 62,
    disciplina: "Geografia",
    assunto: "Hidrografia",
    enunciado: "Como se chama um rio que deságua em outro rio?",
    alternativas: ["Divisor de águas", "Afluente", "Lago", "Oceano"],
    respostaCorreta: 1,
  },
  {
    id: 63,
    disciplina: "Geografia",
    assunto: "Relevo",
    enunciado: "Como se chama uma área de relevo relativamente plana em que predomina a deposição de sedimentos?",
    alternativas: ["Serra", "Montanha", "Planície", "Escarpa"],
    respostaCorreta: 2,
  },
  {
    id: 64,
    disciplina: "Geografia",
    assunto: "Clima e tempo",
    enunciado: "Qual frase descreve uma condição do tempo atmosférico?",
    alternativas: ["Está chovendo nesta cidade agora.", "A região tem clima tropical.", "Os verões da região costumam ser secos.", "O clima local é caracterizado por invernos longos."],
    respostaCorreta: 0,
  },
  {
    id: 65,
    disciplina: "Geografia",
    assunto: "População",
    enunciado: "Como se calcula a densidade demográfica de uma área?",
    alternativas: ["Multiplicando a população pela área.", "Dividindo a área pela população.", "Somando população e área.", "Dividindo a população pela área."],
    respostaCorreta: 3,
  },
  {
    id: 66,
    disciplina: "Geografia",
    assunto: "Urbanização",
    enunciado: "O que caracteriza o êxodo rural?",
    alternativas: ["Migração da cidade para o campo.", "Migração do campo para a cidade.", "Viagem turística entre países.", "Deslocamento diário dentro de um bairro."],
    respostaCorreta: 1,
  },
  {
    id: 67,
    disciplina: "Geografia",
    assunto: "Recursos energéticos",
    enunciado: "Qual destas fontes de energia é renovável?",
    alternativas: ["Carvão mineral", "Petróleo", "Energia solar", "Gás natural"],
    respostaCorreta: 2,
  },
  {
    id: 68,
    disciplina: "Geografia",
    assunto: "Regiões brasileiras",
    enunciado: "A qual região do Brasil pertence o estado do Ceará?",
    alternativas: ["Nordeste", "Norte", "Sudeste", "Sul"],
    respostaCorreta: 0,
  },
  {
    id: 69,
    disciplina: "História",
    assunto: "Brasil colonial",
    enunciado: "Qual atividade econômica ligada à cana-de-açúcar teve destaque no Nordeste durante a colonização portuguesa?",
    alternativas: ["Fabricação de automóveis", "Extração de petróleo", "Produção de açúcar", "Produção de computadores"],
    respostaCorreta: 2,
  },
  {
    id: 70,
    disciplina: "História",
    assunto: "Independência do Brasil",
    enunciado: "Em que ano ocorreu a declaração de independência do Brasil?",
    alternativas: ["1822", "1500", "1889", "1922"],
    respostaCorreta: 0,
  },
  {
    id: 71,
    disciplina: "História",
    assunto: "Abolição da escravidão",
    enunciado: "Qual lei aboliu a escravidão no Brasil em 1888?",
    alternativas: ["Lei de Terras", "Lei do Ventre Livre", "Lei dos Sexagenários", "Lei Áurea"],
    respostaCorreta: 3,
  },
  {
    id: 72,
    disciplina: "História",
    assunto: "República brasileira",
    enunciado: "Em que ano foi proclamada a República no Brasil?",
    alternativas: ["1822", "1889", "1888", "1930"],
    respostaCorreta: 1,
  },
  {
    id: 73,
    disciplina: "História",
    assunto: "Antigo Egito",
    enunciado: "Qual rio foi fundamental para a agricultura do Antigo Egito?",
    alternativas: ["Tigre", "Eufrates", "Nilo", "Danúbio"],
    respostaCorreta: 2,
  },
  {
    id: 74,
    disciplina: "História",
    assunto: "Grécia Antiga",
    enunciado: "Qual cidade grega é conhecida pelo desenvolvimento da democracia na Antiguidade?",
    alternativas: ["Atenas", "Esparta", "Tebas", "Corinto"],
    respostaCorreta: 0,
  },
  {
    id: 75,
    disciplina: "História",
    assunto: "Roma Antiga",
    enunciado: "Qual língua era usada pelos antigos romanos e deu origem ao português?",
    alternativas: ["Grego", "Árabe", "Alemão", "Latim"],
    respostaCorreta: 3,
  },
  {
    id: 76,
    disciplina: "História",
    assunto: "Idade Média",
    enunciado: "Qual relação caracterizava a suserania e a vassalagem no feudalismo europeu?",
    alternativas: ["Contrato de trabalho entre operários.", "Laço de fidelidade e obrigações entre nobres.", "Voto de todos os habitantes para escolher o rei.", "Comércio marítimo entre continentes."],
    respostaCorreta: 1,
  },
  {
    id: 77,
    disciplina: "História",
    assunto: "Renascimento",
    enunciado: "Qual artista do Renascimento pintou a Mona Lisa?",
    alternativas: ["Claude Monet", "Pablo Picasso", "Leonardo da Vinci", "Vincent van Gogh"],
    respostaCorreta: 2,
  },
  {
    id: 78,
    disciplina: "História",
    assunto: "Expansão marítima",
    enunciado: "Qual navegador comandava a expedição portuguesa que chegou ao Brasil em 1500?",
    alternativas: ["Pedro Álvares Cabral", "Cristóvão Colombo", "Fernão de Magalhães", "Bartolomeu Dias"],
    respostaCorreta: 0,
  },
  {
    id: 79,
    disciplina: "História",
    assunto: "Revolução Industrial",
    enunciado: "Em qual país começou a Revolução Industrial no século XVIII?",
    alternativas: ["Brasil", "Japão", "Rússia", "Inglaterra"],
    respostaCorreta: 3,
  },
  {
    id: 80,
    disciplina: "História",
    assunto: "Revolução Francesa",
    enunciado: "Em que ano ocorreu a tomada da Bastilha, marco da Revolução Francesa?",
    alternativas: ["1776", "1789", "1815", "1848"],
    respostaCorreta: 1,
  },
  {
    id: 81,
    disciplina: "História",
    assunto: "Inconfidência Mineira",
    enunciado: "Qual personagem histórico ficou conhecido como Tiradentes?",
    alternativas: ["José Bonifácio de Andrada e Silva", "Joaquim Nabuco", "Joaquim José da Silva Xavier", "Dom Pedro II"],
    respostaCorreta: 2,
  },
  {
    id: 82,
    disciplina: "História",
    assunto: "Primeira Guerra Mundial",
    enunciado: "Em que ano começou a Primeira Guerra Mundial?",
    alternativas: ["1914", "1918", "1939", "1945"],
    respostaCorreta: 0,
  },
  {
    id: 83,
    disciplina: "História",
    assunto: "Segunda Guerra Mundial",
    enunciado: "Em que ano terminou a Segunda Guerra Mundial?",
    alternativas: ["1939", "1942", "1918", "1945"],
    respostaCorreta: 3,
  },
  {
    id: 84,
    disciplina: "História",
    assunto: "Fontes históricas",
    enunciado: "Qual alternativa apresenta um exemplo de fonte histórica escrita?",
    alternativas: ["Um vaso sem inscrições", "Uma carta antiga", "Uma ferramenta de pedra sem inscrições", "Um fóssil de dinossauro"],
    respostaCorreta: 1,
  },
  {
    id: 85,
    disciplina: "Inglês",
    assunto: "Vocabulário",
    enunciado: "Qual é a tradução de 'book' para o português?",
    alternativas: ["Mesa", "Livro", "Janela", "Cadeira"],
    respostaCorreta: 1,
  },
  {
    id: 86,
    disciplina: "Inglês",
    assunto: "Cores",
    enunciado: "Qual palavra em inglês significa 'azul'?",
    alternativas: ["Red", "Green", "Blue", "Yellow"],
    respostaCorreta: 2,
  },
  {
    id: 87,
    disciplina: "Inglês",
    assunto: "Números",
    enunciado: "Como se escreve o número 12 em inglês?",
    alternativas: ["Twelve", "Twenty", "Two", "Ten"],
    respostaCorreta: 0,
  },
  {
    id: 88,
    disciplina: "Inglês",
    assunto: "Pronomes pessoais",
    enunciado: "Qual pronome em inglês corresponde a 'nós'?",
    alternativas: ["They", "He", "You", "We"],
    respostaCorreta: 3,
  },
  {
    id: 89,
    disciplina: "Inglês",
    assunto: "Verbo to be",
    enunciado: "Complete: 'She ___ a teacher.'",
    alternativas: ["Am", "Is", "Are", "Be"],
    respostaCorreta: 1,
  },
  {
    id: 90,
    disciplina: "Inglês",
    assunto: "Verbo to be",
    enunciado: "Complete: 'They ___ happy.'",
    alternativas: ["Is", "Am", "Are", "Be"],
    respostaCorreta: 2,
  },
  {
    id: 91,
    disciplina: "Inglês",
    assunto: "Presente simples",
    enunciado: "Complete: 'He ___ soccer every Saturday.'",
    alternativas: ["Plays", "Play", "Playing", "To play"],
    respostaCorreta: 0,
  },
  {
    id: 92,
    disciplina: "Inglês",
    assunto: "Forma negativa",
    enunciado: "Qual é a forma negativa correta de 'I like coffee'?",
    alternativas: ["I not like coffee.", "I doesn't like coffee.", "I am not like coffee.", "I do not like coffee."],
    respostaCorreta: 3,
  },
  {
    id: 93,
    disciplina: "Inglês",
    assunto: "Plural",
    enunciado: "Qual é o plural de 'child' em inglês?",
    alternativas: ["Childs", "Children", "Childes", "Childrens"],
    respostaCorreta: 1,
  },
  {
    id: 94,
    disciplina: "Inglês",
    assunto: "Artigos",
    enunciado: "Complete: 'This is ___ apple.'",
    alternativas: ["A", "The a", "An", "A an"],
    respostaCorreta: 2,
  },
  {
    id: 95,
    disciplina: "Inglês",
    assunto: "Preposições",
    enunciado: "Em 'The cat is under the table', onde está o gato?",
    alternativas: ["Debaixo da mesa", "Sobre a mesa", "Ao lado da mesa", "Atrás da mesa"],
    respostaCorreta: 0,
  },
  {
    id: 96,
    disciplina: "Inglês",
    assunto: "Dias da semana",
    enunciado: "Qual dia da semana corresponde a 'Monday'?",
    alternativas: ["Domingo", "Terça-feira", "Sexta-feira", "Segunda-feira"],
    respostaCorreta: 3,
  },
  {
    id: 97,
    disciplina: "Inglês",
    assunto: "Saudações",
    enunciado: "Qual expressão significa 'Bom dia' em inglês?",
    alternativas: ["Good night", "Good morning", "Goodbye", "Good afternoon"],
    respostaCorreta: 1,
  },
  {
    id: 98,
    disciplina: "Inglês",
    assunto: "Passado simples",
    enunciado: "Qual é o passado simples do verbo 'go'?",
    alternativas: ["Goed", "Gone", "Went", "Going"],
    respostaCorreta: 2,
  },
  {
    id: 99,
    disciplina: "Inglês",
    assunto: "Compreensão de texto",
    enunciado: "Leia: 'Anna has two brothers and one sister.' Quantos irmãos e irmãs Anna tem ao todo?",
    alternativas: ["Três", "Dois", "Um", "Quatro"],
    respostaCorreta: 0,
  },
  {
    id: 100,
    disciplina: "Inglês",
    assunto: "Palavras interrogativas",
    enunciado: "Qual palavra completa a pergunta sobre lugar: '___ do you live?'",
    alternativas: ["When", "Who", "Why", "Where"],
    respostaCorreta: 3,
  },
];
